name             'hortonworks'
maintainer       'Sam Zen'
maintainer_email 'zensam@ukr.net'
license          'All rights reserved'
description      'Installs/Configures hortonworks'
long_description 'Installs/Configures hortonworks'
version          '0.1.0'

depends 'selinux'
depends 'python'
